### ISSUE TITLE
Сделать регистрацию пользователей.

### ISSUE THREAD

**Issue by belinskidima** [Leproslack/saop#3]
Для регистрации используем гем Devise. Регистрация должна проходить по username а не по e-mail.
Так же нужно иметь возможность изменить привилегии обычного юзера до администратора.

**Comment by kirushik** [comment]
Вот как я бы прописал эту карточку (детали мне сейчас не все понятны, я поэтому додумываю):

> Пользователи должны иметь возможность зарегистрироваться, чтобы получать доступ к внутренним страницам сайта.
> При регистрации необходимо выбрать уникальный адрес электронной почты, задать и подтвердить пароль.
> Пароль должен храниться в базе каким-либо устойчивым к перебору способом (например, scrypt очень хвалят), чтобы при "утекании" базы не происходило потенциального раскрытия пользовательских паролей.
> Юзернейм пользователя генирируется автоматически, из адреса почты (без домена, то есть `kirill@pimenov.cc` превратится просто в `kirill`); в случае не-уникальности такого кастрированного юзернейма — используется почтовый адрес целиком.
> Юзернейм потом можно будет менять, см. карточку [Смена юзернейма в профиле пользователя](#)

Также отсюда ответвляется следующая карточка, отдельная:

Ещё отдельная карточка:

> Некоторые пользователи могут быть Администраторами сайта. Список юзернеймов, которые являются администраторами, задаётся один раз, при запуске приложения (то есть обновляется только при следующем деплое, когда сервер рестартанёт). Список админских юзернеймов допустимо хранить открытым текстом прямо в папке с проектом.

**Comment by kirushik** [comment]
Обратите внимание, что я детально прописываю как что должно себя вести в системе, с точки зрения пользователей и бизнес-логики.
Но при этом вообще по максимуму избегаю конкретных технических решений, максимум что позволяю себе — упомянуть scrypt как предпочтительный метод хеширования паролей. Но если scrypt не подойдёт, то что ж сделать — не завелось, любой другой криптоустойчивый метод тоже подойдёт под карточку. 

И это принципиальный момент. Тот чувак, что пишет фичи, не должен забирать у программистов право на творчество в том, что они любят — в технических решениях. Но в то же время он должен по минимуму оставлять на их совести собственно поведение — иначе получится очередной супермонстр с дюжиной табов для галочек настройки.

**Comment by zelcam** [comment]
комменты к созданию
1. все юзеры создаются учетной записью администратора
2. существует  два типа юзеров - мерчендайзер (юзер) и менеджер (возможности менеджера см в карточке возможности менеджера)

**Comment by zelcam** [comment]
scrypt done
боженька, накажи того, кто писал под него доки

**Comment by zelcam** [comment]
регистрация и вход по емейлу\логину done
добавлены булеаны менеджер, админ.
сделаем админку - сделаю под это кнопки.
